### ISSUE TITLE
字之间出现混淆

### ISSUE THREAD

**Issue by wellgpt** [ShqWW/bilinovel-download#10]
似乎解密方式该更新了，字已经乱了

已经严重影响阅读，我看到的文字都是这样的：
![捕获](https://github.com/ShqWW/bilinovel-download/assets/171525738/9cf7b893-6e70-485a-90b6-794efe99653d)
或许大佬可以改为只抓取文字而忽略格式，这样乱码问题应该也能解决吧

**Comment by wellgpt** [comment]
有关字体混淆表：https://github.com/sweetnotice/Bilinoval_DL

**Comment by 2655196510** [comment]
确实，好像每章的最后一段都做了加密
![捕获](https://github.com/user-attachments/assets/2ebc4d16-29f1-4e2a-b534-0e92a52d1a39)

**Comment by 2655196510** [comment]
上面的参考的是这个https://github.com/lightnovel-center/linovelib2epub/blob/main/docs-internal/linovelib-pc-font-obfuscation.md

**Comment by ShqWW** [comment]
已修复
