### ISSUE TITLE
爬不到书籍目录

### ISSUE THREAD

**Issue by amane64** [ShqWW/bilinovel-download#13]
目录页地址加了cloudflare人机验证，拿不到了
![image](https://github.com/user-attachments/assets/c8756bef-d472-4b1d-872b-815e34491209)
![Snipaste_2024-11-05_12-14-04](https://github.com/user-attachments/assets/43e2734f-8922-4141-9ecc-2ec8101315b4)

**Comment by amane64** [comment]
有一个方法：
https://www.linovelib.com/novel/书id/catalog会被拦截
但是https://www.linovelib.com/novel/书id/随便六位数.html不会

**Comment by ShqWW** [comment]
ip原因 挂梯子或着换ip。
