### ISSUE TITLE
透過打包EXE下載的EPUB書籍無內容

### ISSUE THREAD

**Issue by aaron988025** [ShqWW/bilinovel-download#14]
最近透過Release打包的EXE 進行書籍的下載，發現下載的EPUB內容都是空的，不確定是不是改規則了?!
另外有嘗試把延遲秒數調高也是會有同樣的狀況。

**Comment by Leonoves** [comment]
楼主解决了吗 我的下载epub之后打开目录完整但内容全是none

**Comment by kotorimiku** [comment]
把Editer.py文件的198行的'class': 'acontent'改为'class': 'bcontent'就可以下了,不过现在好像会封ip了

**Comment by aaron988025** [comment]
因為我適用打包好的exe，沒直接使用python去測試，所以還不知道狀況。

**Comment by ShqWW** [comment]
确实改规则了 加了cf验证 以及正文class 和id发生改变

**Comment by aaron988025** [comment]
這個有機會修正嗎? 在麻煩您了!

**Comment by ShqWW** [comment]
> 這個有機會修正嗎? 在麻煩您了!

已经修了 但是考虑到即使修好那边也会反爬暂时先不放

**Comment by aaron988025** [comment]
好的，非常謝謝您!!

**Comment by aaron988025** [comment]
現在爬好像都會被Ban 變成 HTTP 403... 不知道會不會回復正常... 希望不是永Ban

**Comment by ShqWW** [comment]
尝试延长时间间隔或更换ip
