### ISSUE TITLE
下载六、七卷书后无法正常下载

### ISSUE THREAD

**Issue by chaochao03x** [ShqWW/bilinovel-download#3]
可能被反爬了，下载过程中的xhtml文档和最后的epub文件都只有标题，正文只有None，没有图片
![微信截图_20231122214024](https://github.com/ShqWW/bilinovel-download/assets/73626814/ae38b6a0-285c-4b23-8d75-50b9db3f09c2)

![微信截图_20231122213832](https://github.com/ShqWW/bilinovel-download/assets/73626814/6e6ced0f-af60-4a48-a94f-51669f457ad8)

**Comment by ShqWW** [comment]
已经修复
