### ISSUE TITLE
章节的最后一段出现乱码

### ISSUE THREAD

**Issue by Krysl** [ShqWW/bilinovel-download#6]
似乎会在该章不止1页时有这现象

**Comment by c870620096** [comment]
是的，好像是那种镶嵌字体就会这样

**Comment by Krysl** [comment]
一个月前简单研究过，好像是要换成一个read.woff2的字体。
本来一卷就两三M体积，加个1.7M的字体也太占空间。
https://www.bilinovel.com 那网站就没字体问题，你这库我简单修改了几处就适配上了。

**Comment by ShqWW** [comment]
已修复
